//Generated by 24HRS
function getRow() {
	var table = document.getElementById('table');
	for (var i = 0; i < table.rows.length; i++) {
		table.rows[i].onclick = function() {
			document.getElementById("payment_id").value = this.cells[1].textContent;
			document.getElementById("name_on_card").value = this.cells[2].textContent;
			document.getElementById("card_number").value = this.cells[3].textContent;
			document.getElementById("cvv").value = this.cells[4].textContent;
			document.getElementById("exp_day").value = this.cells[5].textContent;
			document.getElementById("amout").value = this.cells[6].textContent;
		};
	}
}

function getRowSearch() {
	var table = document.getElementById('idTable');
	for (var i = 0; i < table.rows.length; i++) {
		table.rows[i].onclick = function() {
			document.getElementById("payment_id").value = this.cells[1].textContent;
			document.getElementById("name_on_card").value = this.cells[2].textContent;
			document.getElementById("card_number").value = this.cells[3].textContent;
			document.getElementById("cvv").value = this.cells[4].textContent;
			document.getElementById("exp_day").value = this.cells[5].textContent;
			document.getElementById("amout").value = this.cells[6].textContent;
		};
	}
}

function getID() {
	var table = document.getElementById('table');
	for (var i = 0; i < table.rows.length; i++) {
		table.rows[i].onclick = function() {
			document.getElementById("payment_id").value = this.cells[1].textContent;
		};
	}
}

function getIDserch() {
	var table = document.getElementById('idTable');
	for (var i = 0; i < table.rows.length; i++) {
		table.rows[i].onclick = function() {
			document.getElementById("payment_id").value = this.cells[1].textContent;
		};
	}
}

function resetForm() {
	document.getElementById("payment_id").value = "0";
	document.getElementById("name_on_card").value = "";
	document.getElementById("card_number").value = "";
	document.getElementById("cvv").value = "";
	document.getElementById("exp_day").value = "";
	document.getElementById("amout").value = "";
}

function save() {
	var payment_id = $('#payment_id').val();
	payment_id = parseInt(payment_id);
	if (payment_id === 0) {
		if(ValidInput()){
			$.ajax({
				url : 'http://localhost:8080/payment/webresources/Payment_managementResources/Payment_management',
				method : 'POST',
				headers : {
					"Content-Type" : "application/json"
				},
				data : getJSON(),
				success : function(data) {
					$("#idTable").find("tr:gt(0)").remove();
					$("#table").find("tr:gt(0)").remove();
					load();
					resetForm();
					alert(data);
				},
				error : function(jqXHR, exception) {
					alert("error");
				}
			});
		}else{
			alert("Fill form");
		}
	}else{
		if(ValidInput()){
			$.ajax({
				url : 'http://localhost:8080/payment/webresources/Payment_managementResources/Payment_management',
				method : 'PUT',
				headers : {
					"Content-Type" : "application/json"
				},
				data : getJSON(),
				success : function(data) {
					$("#idTable").find("tr:gt(0)").remove();
					$("#table").find("tr:gt(0)").remove();
					load();
					resetForm();
					alert(data);
				},
				error : function(jqXHR, exception) {
					alert("error");
				}
			});
		}else{
			alert("Fill form");
		}
	}
}

function delet(){
	getID();
	swal({
		title: "Are you sure?",
		text: "Do you realy want to Delete this?",
		icon: "warning",
		buttons: true,
		dangerMode: true,
	})
		.then((willDelete) => {
			if (willDelete) {
				$.ajax({
					url : 'http://localhost:8080/payment/webresources/Payment_managementResources/Payment_management/' + $('#payment_id').val(),
					method: 'DELETE',
					success: function (resultText) {
						$("#table").find("tr:gt(0)").remove();
						$("#idTable").find("tr:gt(0)").remove();
						load();
						swal("Deleted!", {
							icon: "success",
							});
						},
						error: function (jqXHR, exception) {
							swal("fail");
						}
					});
				} else {
					swal("Safe!");
				}
			});
}

function deletSearch(){
	getIDserch();
	swal({
		title: "Are you sure?",
		text: "Do you realy want to Delete this?",
		icon: "warning",
		buttons: true,
		dangerMode: true,
	})
		.then((willDelete) => {
			if (willDelete) {
				$.ajax({
					url : 'http://localhost:8080/payment/webresources/Payment_managementResources/Payment_management/' + $('#payment_id').val(),
					method: 'DELETE',
					success: function (resultText) {
						$("#table").find("tr:gt(0)").remove();
						$("#idTable").find("tr:gt(0)").remove();
						load();
						swal("Deleted!", {
							icon: "success",
							});
						},
						error: function (jqXHR, exception) {
							swal("fail");
						}
					});
				} else {
					swal("Safe!");
				}
			});
}

function load() {
	$.ajax({
		url : 'http://localhost:8080/payment/webresources/Payment_managementResources/Payment_managements',
		method : 'GET',
		headers : {
			Accept : "application/json",
			"Content-Type" : "application/json"
		},
		success : function(data, textStatus, errorThrown) {
			var items = [];
			$.each(data.paymentManagement,function(key, val) {
				var index = key + 1;
				items.push("<tr>");
				items.push("<td>" + index + "</td>");
				items.push("<td>" + val.payment_id + "</td>");
				items.push("<td>" + val.name_on_card + "</td>");
				items.push("<td>" + val.card_number + "</td>");
				items.push("<td>" + val.cvv + "</td>");
				items.push("<td>" + val.exp_day + "</td>");
				items.push("<td>" + val.amout + "</td>");
				items.push("<td><button onclick='getRow()' type='button' class='btn btn-info btn-fill'>Edit</button></td>");
				items.push("<td><button onclick='delet()' type='button' class='btn btn-danger btn-fill'>Delete</button></td>");
				items.push("</tr>");
			});
		$("<tbody/>", {
			html : items.join("")
		}).appendTo("#table");
		},
		error : function(jqXHR, textStatus, errorThrown) {
			alert("Ajax request fail");
		},
		timeout : 120000,
	});
}

function getJSON() {
	return JSON.stringify({
		"payment_id" : $('#payment_id').val(),
		"name_on_card" : $('#name_on_card').val(),
		"card_number" : $('#card_number').val(),
		"cvv" : $('#cvv').val(),
		"exp_day" : $('#exp_day').val(),
		"amout" : $('#amout').val(),
	});
}

function ValidInput(){
	var payment_id = $('#payment_id').val();
	var name_on_card = $('#name_on_card').val();
	var card_number = $('#card_number').val();
	var cvv = $('#cvv').val();
	var exp_day = $('#exp_day').val();
	var amout = $('#amout').val();
	var payment_id = $('#payment_id').val();
	var name_on_card = $('#name_on_card').val();
	var card_number = $('#card_number').val();
	var cvv = $('#cvv').val();
	var exp_day = $('#exp_day').val();
	var amout = $('#amout').val();
	if(payment_id === "" || name_on_card === "" || card_number === "" || cvv === "" || exp_day === "" || amout === ""){
		return false;
	}else{
		return true;
	}
	return true;
}

function search(){
$("#idTable").find("tr:gt(0)").remove();
	var searchID = $('#searchID').val();
	if(searchID === ""){
		alert("Please Enter ID")
	}else{
	$.ajax({
		url : 'http://localhost:8080/payment/webresources/Payment_managementResources/Payment_management/' + searchID,
		method : 'GET',
		headers : {
			Accept : "application/json",
			"Content-Type" : "application/json"
		},
		success : function(data, textStatus, errorThrown) {
			var items = [];
			$.each(data,function(key, val) {
				var index = key + 1;
				items.push("<tr>");
				items.push("<td>" + index + "</td>");
				items.push("<td>" + val.payment_id + "</td>");
				items.push("<td>" + val.name_on_card + "</td>");
				items.push("<td>" + val.card_number + "</td>");
				items.push("<td>" + val.cvv + "</td>");
				items.push("<td>" + val.exp_day + "</td>");
				items.push("<td>" + val.amout + "</td>");
				items.push("<td><button onclick='getRow()' type='button' class='btn btn-info btn-fill'>Edit</button></td>");
				items.push("<td><button onclick='delet()' type='button' class='btn btn-danger btn-fill'>Delete</button></td>");
				items.push("</tr>");
			});
		$("<tbody/>", {
			html : items.join("")
		}).appendTo("#idTable");
	},
		error : function(jqXHR, textStatus, errorThrown) {
			alert("Ajax request fail");
		},
		timeout : 120000,
		});
	}
}